<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-24T07:40:29Z" name="Suite" finished-at="2025-02-24T07:41:06Z" duration-ms="37244">
    <groups>
    </groups>
    <test started-at="2025-02-24T07:40:29Z" name="Run on FIREFOX browser" finished-at="2025-02-24T07:41:06Z" duration-ms="37244">
      <class name="nopCommerce.user.User_Login">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:nopCommerce.user.User_Login@2aceadd4]" started-at="2025-02-24T07:40:50Z" name="beforeClass" finished-at="2025-02-24T07:41:00Z" duration-ms="10921" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="Login_06_Valid_Login()[pri:0, instance:nopCommerce.user.User_Login@2aceadd4]" started-at="2025-02-24T07:41:00Z" name="Login_06_Valid_Login" finished-at="2025-02-24T07:41:06Z" duration-ms="5776" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_06_Valid_Login -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:nopCommerce.user.User_Login@2aceadd4]" started-at="2025-02-24T07:41:06Z" name="afterClass" finished-at="2025-02-24T07:41:06Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- nopCommerce.user.User_Login -->
      <class name="nopCommerce.user.User_Register">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:nopCommerce.user.User_Register@24269709]" started-at="2025-02-24T07:40:29Z" name="beforeClass" finished-at="2025-02-24T07:40:45Z" duration-ms="15873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="TC_03_Register_Success()[pri:0, instance:nopCommerce.user.User_Register@24269709]" started-at="2025-02-24T07:40:45Z" name="TC_03_Register_Success" finished-at="2025-02-24T07:40:50Z" duration-ms="4643" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thank you for registering with Main Website Store..] but found [Thank you for registering with Main Website Store.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thank you for registering with Main Website Store..] but found [Thank you for registering with Main Website Store.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at nopCommerce.user.User_Register.TC_03_Register_Success(User_Register.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_Register_Success -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:nopCommerce.user.User_Register@24269709]" started-at="2025-02-24T07:40:50Z" name="afterClass" finished-at="2025-02-24T07:40:50Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- nopCommerce.user.User_Register -->
    </test> <!-- Run on FIREFOX browser -->
  </suite> <!-- Suite -->
</testng-results>
